# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: "My Pull Requests"
    filters: "is:open author:@me"
issuesSections:
  - title: "My Issues"
    filters: "is:open author:@me"
