# Fix colors for Neovim / Starship (TrueColor support)
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-sessionx'

# Run TPM
run '~/.tmux/plugins/tpm/tpm'

# SessionX configuration
set -g @sessionx-bind 'C-t'
set -g @sessionx-custom-paths '/Users/alfred/git,/Users/alfred/git-templates,/Users/alfred/remotes'
set -g @sessionx-window-mode 'on'
set -g @sessionx-git-branch 'on'

set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set-option -g default-shell "/bin/zsh"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

set -g status-style 'bg=#1e1e2e fg=#cdd6f4'

set -g status-left " #[fg=#89b4fa,bold]Session: #S "
set -g status-right " #[fg=#fab387]%H:%M "

set -g window-status-current-style 'fg=#a6e3a1 bold'
set -g window-status-current-format ' #I #W '

set -g window-status-style 'fg=#6c7086'
set -g window-status-format ' #I #W '
